add_newline = false
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](purple)"

[cmd_duration]
format = "[$duration]($style) "
